language: node_js
node_js:
- lts/*
script:
- npm run build

cache:
  directories:
  - node_modules

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -avzhe ssh ./dist/ hao@vul.haoxp.xyz:/home/hao/tech_blog
    on:
      branch: master

before_deploy:
- openssl aes-256-cbc -K $encrypted_15323a3d3502_key -iv $encrypted_15323a3d3502_iv
  -in deploy_tmp.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- ssh-keyscan vul.haoxp.xyz >> ~/.ssh/known_hosts