export const backendPrefix = 'https://wukong.leeleo.me'
export const wsPrefix = 'wss://wukong.leeleo.me'
export const lcSongList = 'WUKONG_LOCAL_SONGLIST'
export const lcMuted = 'WUKONG_LOCAL_MUTED'
export const lcUseCDN = 'WUKONG_LOCAL_USECDN'
